# Server Configuration
server.port=1998

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://35.244.60.117:5432/mydb?sslmode=disable&sslfactory=org.postgresql.ssl.NonValidatingFactory&preferQueryMode=simple
spring.datasource.username=postgres
spring.datasource.password=Mydb1298@
spring.datasource.hikari.allow-pool-suspension=true
spring.datasource.hikari.autoCommit=true
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.generate-ddl=false
spring.jpa.open-in-view=false

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Security Configuration
spring.security.user.name=sa
spring.security.user.password=

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=3600
jwt.refresh-expiration=86400

# Notification Service Configuration
notification.service.url=http://localhost:8000/api/notifications/process

# Google Cloud PubSub Configuration
spring.cloud.gcp.project-id=telus-koodo
spring.cloud.gcp.credentials.location=classpath:telus-koodo-cfa313a81d01.json
spring.cloud.gcp.pubsub.enabled=true
pubsub.topic.user-registration=UserRegisterEvent
pubsub.topic.account-approved=AccountApprovedEvent

# Logging Configuration
#logging.level.root=DEBUG
#logging.level.com.example.authentication=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.jdbc.datasource.init=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework=DEBUG

# File logging
logging.file.name=logs/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
