spring.profiles.active=dev
notification.service.url=https://notification-service-865090871947.asia-south1.run.app

# OneLogin OAuth2 Configuration
onelogin.client-id=a3222460-4a99-013e-14ba-0d5aef30bcb1250692
onelogin.client-secret=b815329bee29a2224f27f37da7f1a01c7e02ae23e0bea6ab518cb486083ad738
onelogin.token-url=https://telusrecruitai.onelogin.com/oidc/2/token
onelogin.redirect-uri=https://telusrecruitai-865090871947.asia-south1.run.app/callback

# Spring Security OAuth2 Configuration
spring.security.oauth2.client.registration.onelogin.client-id=${onelogin.client-id}
spring.security.oauth2.client.registration.onelogin.client-secret=${onelogin.client-secret}
spring.security.oauth2.client.registration.onelogin.scope=openid,profile,email
spring.security.oauth2.client.registration.onelogin.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.onelogin.client-authentication-method=client_secret_basic

# OneLogin Provider Configuration
spring.security.oauth2.client.provider.onelogin.token-uri=${onelogin.token-url}
spring.security.oauth2.client.provider.onelogin.authorization-uri=https://telusrecruitai.onelogin.com/auth/oauth2/v2/authorize
spring.security.oauth2.client.provider.onelogin.user-info-uri=https://telusrecruitai.onelogin.com/auth/oauth2/v2/userinfo
spring.security.oauth2.client.provider.onelogin.jwk-set-uri=https://telusrecruitai.onelogin.com/auth/oauth2/v2/keys
