spring.profiles.active=dev
notification.service.url=https://notification-service-865090871947.asia-south1.run.app

# OneLogin OAuth2 Configuration
onelogin.client-id=811abdb0-4b5e-013e-0f7b-7b334b1018e4176721
onelogin.client-secret=bc6eb98bec7e5887e3964fac590540c619f6833af5e9e53686b6055f56a0e128
onelogin.token-url=https://telus-sandbox.onelogin.com/oidc/2/token
onelogin.redirect-uri=https://telusrecruitai-865090871947.asia-south1.run.app/callback

# Spring Security OAuth2 Configuration
spring.security.oauth2.client.registration.onelogin.client-id=${onelogin.client-id}
spring.security.oauth2.client.registration.onelogin.client-secret=${onelogin.client-secret}
spring.security.oauth2.client.registration.onelogin.scope=openid,profile,email
spring.security.oauth2.client.registration.onelogin.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.onelogin.client-authentication-method=client_secret_basic

# OneLogin Provider Configuration
spring.security.oauth2.client.provider.onelogin.token-uri=${onelogin.token-url}
spring.security.oauth2.client.provider.onelogin.authorization-uri=https://telusrecruitai.onelogin.com/auth/oauth2/v2/authorize
spring.security.oauth2.client.provider.onelogin.user-info-uri=https://telusrecruitai.onelogin.com/auth/oauth2/v2/userinfo
spring.security.oauth2.client.provider.onelogin.jwk-set-uri=https://telusrecruitai.onelogin.com/auth/oauth2/v2/keys
